pipeline {
    agent any

    stages {

        stage('Environment') {
            steps {
                sh 'echo "Hello from Jenkins"'
                sh 'pwd'
            }
        }

        stage('Build') {
            steps {
                sh 'echo "Building..."'
            }
        }

        stage('Test') {
            steps {
                sh 'echo "Testing..."'
            }
        }
    }
}


// Scripted
// node {
//     stage('Build') {
//         echo 'Building'
//     }
// }

// More flexible and programming-oriented